### ISSUE TITLE
Mentor Client

### ISSUE THREAD

**Issue by Arfarafar** [timattt/Project-Cognitia-II#9]
![image](https://user-images.githubusercontent.com/45181367/136822845-886982a1-68b6-4e3d-9c6f-181468562932.png)

1) Выезжающее слева окно со списком всех студентов, выбранный студент отмечен в нем, можно выбрать другого студента для оценивания

2) выезжающее справа окно чата со студентом при нажатии на юнит. 

3) выезжающее окно микшера снизу, микшер либо в круглой либо в вертикальной форме.
кнопка сохранить и отправить на сервер

**Comment by timattt** [comment]
все сделал, только виджеты не выезжают. Потому что это не удобно. Когда каждый раз нажимаешь на вершину.
